import type { ExternalMission } from '@/features/missions/solidarityMissions';

// Ligne external_missions complète (valeurs neutres) pour les tests.
export function externalMissionRow(overrides: Partial<ExternalMission> = {}): ExternalMission {
  return {
    id: 'ext-1',
    source: 'api_engagement',
    external_id: '66f1a2b3c4d5e6f7a8b9c0d1',
    client_id: 'mission-123',
    publisher_id: '5f5931496c7ea514150a818f',
    publisher_name: 'JeVeuxAider.gouv.fr',
    publisher_url: 'https://www.jeveuxaider.gouv.fr',
    publisher_logo_url: null,
    mission_type: 'benevolat',
    domain: 'solidarite-insertion',
    activities: [],
    status_code: 'ACCEPTED',
    remote: 'no',
    title: 'Distribution de colis alimentaires',
    description: 'Aider à préparer les colis.',
    organization_name: 'Banque Alimentaire',
    organization_logo_url: null,
    organization_url: null,
    organization_rna: null,
    organization_siren: null,
    organization_status_juridique: null,
    image_url: null,
    source_illustration_url: 'https://cdn.example.org/domain.png',
    category: 'aide_alimentaire',
    city: 'Lille',
    postal_code: '59000',
    department_code: '59',
    address: 'Fives',
    lat: 50.63,
    lng: 3.09,
    starts_at: '2026-10-03T07:00:00Z',
    ends_at: '2026-10-03T10:00:00Z',
    schedule_text: null,
    duration_minutes: 180,
    places: 8,
    application_url: 'https://api.api-engagement.beta.gouv.fr/r/66f1a2b3c4d5e6f7a8b9c0d1/65aa00000000000000000001',
    source_url: null,
    is_active: true,
    source_created_at: null,
    source_updated_at: null,
    source_deleted_at: null,
    last_seen_at: '2026-09-20T00:00:00Z',
    raw: null,
    imported_at: '2026-09-20T00:00:00Z',
    updated_at: '2026-09-20T00:00:00Z',
    ...overrides,
  };
}
