-- Durcissement du parcours KYC travailleur.
--
-- Objectifs :
-- - aucun utilisateur ne peut s'auto-marquer comme verifie ;
-- - la soumission passe par une RPC et reference un objet réellement present
--   dans le bucket privé ;
-- - les decisions sont reservees aux comptes fondateurs explicitement
--   autorises et sont journalisees ;
-- - le retrait du wallet reste impossible tant que le KYC n'est pas verifie.

-- Preserve l'acces du compte fondateur historique avant de supprimer le
-- contournement par email et le code partage.
insert into public.founder_access (user_id)
select u.id
from auth.users u
where lower(u.email) = 'fodesanoussy178@gmail.com'
on conflict (user_id) do nothing;

create or replace function public.has_founder_access()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and (
      coalesce((auth.jwt() -> 'app_metadata' ->> 'is_founder')::boolean, false)
      or exists (
        select 1
        from public.founder_access fa
        where fa.user_id = (select auth.uid())
      )
    )
$$;

create or replace function public.is_founder()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.has_founder_access()
$$;

-- Le code partage ne doit jamais permettre une elevation de privilege.
revoke execute on function public.claim_founder_access(text) from public, anon, authenticated;
drop function public.claim_founder_access(text);
revoke execute on function public.has_founder_access() from public, anon;
revoke execute on function public.is_founder() from public, anon;
grant execute on function public.has_founder_access() to authenticated;
grant execute on function public.is_founder() to authenticated;

-- Les champs de contournement structure ne peuvent pas etre fabriques par
-- une ecriture directe depuis le navigateur.
create or replace function public.guard_structure_verification_fields()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (
    new.founder_bypass is true
    or new.verification_status = 'founder_bypass'
    or new.verification_method = 'founder'
  ) and not public.is_founder() then
    raise exception using
      errcode = '42501',
      message = 'Acces fondateur requis pour ce contournement.';
  end if;
  return new;
end;
$$;

drop trigger if exists structures_guard_verification on public.structures;
create trigger structures_guard_verification
  before insert or update of verification_status, verification_method, founder_bypass
  on public.structures
  for each row execute function public.guard_structure_verification_fields();

-- Historique immuable des changements KYC.
create table if not exists public.kyc_status_history (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles (id) on delete cascade,
  previous_status text,
  new_status text not null,
  reason text,
  source text not null default 'system',
  changed_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  constraint kyc_status_history_previous_check
    check (previous_status is null or previous_status in ('not_started', 'requested', 'submitted', 'verified', 'rejected')),
  constraint kyc_status_history_new_check
    check (new_status in ('not_started', 'requested', 'submitted', 'verified', 'rejected')),
  constraint kyc_status_history_source_check
    check (source in ('system', 'mission_acceptance', 'worker_submit', 'founder_review'))
);

create index if not exists kyc_status_history_profile_created_idx
  on public.kyc_status_history (profile_id, created_at desc);

alter table public.kyc_status_history enable row level security;

drop policy if exists "kyc history: owner or founder read" on public.kyc_status_history;
create policy "kyc history: owner or founder read"
  on public.kyc_status_history for select
  to authenticated
  using (profile_id = (select auth.uid()) or (select public.is_founder()));

revoke all on table public.kyc_status_history from public, anon;
grant select on table public.kyc_status_history to authenticated;

-- Protege les colonnes d'autorisation et les donnees KYC contre les UPDATE
-- directs. Les transitions legitimes passent par les fonctions ci-dessous.
create or replace function public.guard_profile_protected_fields()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_source text := coalesce(current_setting('app.kyc_source', true), '');
  v_kyc_changed boolean;
begin
  if new.id is distinct from old.id
     or new.role is distinct from old.role
     or new.created_at is distinct from old.created_at then
    raise exception using
      errcode = '42501',
      message = 'Les champs système du profil ne sont pas modifiables.';
  end if;

  v_kyc_changed :=
    new.kyc_status is distinct from old.kyc_status
    or new.kyc_requested_at is distinct from old.kyc_requested_at
    or new.kyc_submitted_at is distinct from old.kyc_submitted_at
    or new.iban_country is distinct from old.iban_country
    or new.iban_last4 is distinct from old.iban_last4
    or new.identity_document_name is distinct from old.identity_document_name
    or new.identity_document_path is distinct from old.identity_document_path
    or new.identity_document_uploaded_at is distinct from old.identity_document_uploaded_at;

  if not v_kyc_changed then
    return new;
  end if;

  -- Migrations, service_role et triggers internes de ce fichier.
  if v_uid is null or v_source in ('mission_acceptance', 'worker_submit', 'founder_review') then
    return new;
  end if;

  if public.is_founder() then
    return new;
  end if;

  raise exception using
    errcode = '42501',
    message = 'Utilisez le parcours KYC sécurisé pour modifier ces informations.';
end;
$$;

drop trigger if exists profiles_guard_protected_fields on public.profiles;
create trigger profiles_guard_protected_fields
  before update on public.profiles
  for each row execute function public.guard_profile_protected_fields();

create or replace function public.log_kyc_status_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_source text := coalesce(nullif(current_setting('app.kyc_source', true), ''), 'system');
  v_reason text := nullif(current_setting('app.kyc_reason', true), '');
begin
  if new.kyc_status is distinct from old.kyc_status then
    insert into public.kyc_status_history (
      profile_id, previous_status, new_status, reason, source, changed_by
    ) values (
      new.id, old.kyc_status, new.kyc_status, v_reason, v_source, auth.uid()
    );
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_log_kyc_status on public.profiles;
create trigger profiles_log_kyc_status
  after update of kyc_status on public.profiles
  for each row execute function public.log_kyc_status_change();

-- La demande KYC apparait uniquement apres l'acceptation d'une candidature.
create or replace function public.request_kyc_after_acceptance()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status = 'accepted' and old.status is distinct from 'accepted' then
    perform set_config('app.kyc_source', 'mission_acceptance', true);
    update public.profiles
    set kyc_status = 'requested',
        kyc_requested_at = coalesce(kyc_requested_at, now())
    where id = new.worker_id
      and role = 'worker'
      and kyc_status in ('not_started', 'rejected');
  end if;
  return new;
end;
$$;

drop trigger if exists applications_request_worker_kyc on public.applications;
create trigger applications_request_worker_kyc
  after update of status on public.applications
  for each row execute function public.request_kyc_after_acceptance();

-- Backfill des candidatures deja acceptees sans modifier les profils soumis
-- ou verifies.
select set_config('app.kyc_source', 'mission_acceptance', true);
update public.profiles p
set kyc_status = 'requested',
    kyc_requested_at = coalesce(p.kyc_requested_at, now())
where p.role = 'worker'
  and p.kyc_status = 'not_started'
  and exists (
    select 1
    from public.applications a
    where a.worker_id = p.id
      and a.status in ('accepted', 'in_progress', 'payment_pending', 'completed')
  );
select set_config('app.kyc_source', '', true);

-- Soumission atomique : ne stocke jamais l'IBAN complet et exige que le
-- document existe dans le dossier du demandeur.
create or replace function public.submit_worker_kyc(
  p_iban_country text,
  p_iban_last4 text,
  p_document_name text,
  p_document_path text
)
returns public.profiles
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_profile public.profiles;
  v_country text := upper(btrim(coalesce(p_iban_country, '')));
  v_last4 text := upper(btrim(coalesce(p_iban_last4, '')));
  v_name text := btrim(coalesce(p_document_name, ''));
  v_path text := btrim(coalesce(p_document_path, ''));
begin
  if v_uid is null then
    raise exception using errcode = '42501', message = 'Authentification requise.';
  end if;
  if v_country !~ '^[A-Z]{2}$' or v_last4 !~ '^[A-Z0-9]{4}$' then
    raise exception using errcode = '22023', message = 'Informations IBAN invalides.';
  end if;
  if length(v_name) < 3 or length(v_name) > 160 then
    raise exception using errcode = '22023', message = 'Nom de document invalide.';
  end if;
  if v_path not like v_uid::text || '/%' then
    raise exception using errcode = '42501', message = 'Chemin de document invalide.';
  end if;
  if not exists (
    select 1 from storage.objects o
    where o.bucket_id = 'kyc-documents' and o.name = v_path
  ) then
    raise exception using errcode = '22023', message = 'Document KYC introuvable.';
  end if;

  perform set_config('app.kyc_source', 'worker_submit', true);
  update public.profiles
  set kyc_status = 'submitted',
      kyc_requested_at = coalesce(kyc_requested_at, now()),
      kyc_submitted_at = now(),
      iban_country = v_country,
      iban_last4 = v_last4,
      identity_document_name = v_name,
      identity_document_path = v_path,
      identity_document_uploaded_at = now()
  where id = v_uid
    and role = 'worker'
    and kyc_status in ('requested', 'rejected')
  returning * into v_profile;

  if not found then
    raise exception using errcode = '23514', message = 'Aucune demande KYC active pour ce compte.';
  end if;
  return v_profile;
end;
$$;

revoke execute on function public.submit_worker_kyc(text, text, text, text) from public, anon;
grant execute on function public.submit_worker_kyc(text, text, text, text) to authenticated;

-- Outils de revue manuelle, disponibles uniquement aux comptes explicitement
-- inscrits dans founder_access (ou app_metadata.is_founder=true).
create or replace function public.founder_list_kyc_submissions()
returns table (
  profile_id uuid,
  full_name text,
  kyc_status text,
  kyc_requested_at timestamptz,
  kyc_submitted_at timestamptz,
  iban_country text,
  iban_last4 text,
  identity_document_name text,
  identity_document_path text,
  identity_document_uploaded_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_founder() then
    raise exception using errcode = '42501', message = 'Acces fondateur requis.';
  end if;
  return query
  select p.id, p.full_name, p.kyc_status, p.kyc_requested_at,
         p.kyc_submitted_at, p.iban_country, p.iban_last4,
         p.identity_document_name, p.identity_document_path,
         p.identity_document_uploaded_at
  from public.profiles p
  where p.role = 'worker' and p.kyc_status <> 'not_started'
  order by p.kyc_submitted_at desc nulls last, p.kyc_requested_at desc nulls last;
end;
$$;

create or replace function public.founder_set_kyc_status(
  p_profile_id uuid,
  p_status text,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_reason text := nullif(btrim(coalesce(p_reason, '')), '');
begin
  if not public.is_founder() then
    raise exception using errcode = '42501', message = 'Acces fondateur requis.';
  end if;
  if p_status not in ('verified', 'rejected') then
    raise exception using errcode = '22023', message = 'Decision KYC invalide.';
  end if;
  if p_status = 'rejected' and v_reason is null then
    raise exception using errcode = '22023', message = 'Un motif est requis pour refuser.';
  end if;

  perform set_config('app.kyc_source', 'founder_review', true);
  perform set_config('app.kyc_reason', coalesce(v_reason, ''), true);
  update public.profiles
  set kyc_status = p_status
  where id = p_profile_id and role = 'worker' and kyc_status = 'submitted';

  if not found then
    raise exception using errcode = '23514', message = 'Ce dossier KYC ne peut pas etre traite.';
  end if;
end;
$$;

revoke execute on function public.founder_list_kyc_submissions() from public, anon;
revoke execute on function public.founder_set_kyc_status(uuid, text, text) from public, anon;
grant execute on function public.founder_list_kyc_submissions() to authenticated;
grant execute on function public.founder_set_kyc_status(uuid, text, text) to authenticated;

-- Bucket strictement prive, sans remplacement ni suppression par le client.
update storage.buckets
set public = false,
    file_size_limit = 10485760,
    allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
where id = 'kyc-documents';

drop policy if exists "kyc owners can upload" on storage.objects;
create policy "kyc owners can upload"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'kyc-documents'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "kyc owners can read" on storage.objects;
create policy "kyc owners can read"
on storage.objects for select to authenticated
using (
  bucket_id = 'kyc-documents'
  and (
    (storage.foldername(name))[1] = (select auth.uid())::text
    or (select public.is_founder())
  )
);

drop policy if exists "kyc owners can replace" on storage.objects;
drop policy if exists "kyc owners can delete" on storage.objects;

-- Derniere barriere : meme un appel direct a la RPC de retrait est refuse
-- tant que le travailleur n'est pas verifie.
create or replace function public.require_verified_kyc_for_withdrawal()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.kind = 'withdrawal' and exists (
    select 1
    from public.wallets w
    join public.profiles p on p.id = w.profile_id
    where w.id = new.wallet_id
      and p.role = 'worker'
      and p.kyc_status <> 'verified'
  ) then
    raise exception using
      errcode = '23514',
      message = 'Verification KYC requise avant tout retrait.';
  end if;
  return new;
end;
$$;

drop trigger if exists wallet_transactions_require_verified_kyc on public.wallet_transactions;
create trigger wallet_transactions_require_verified_kyc
  before insert on public.wallet_transactions
  for each row execute function public.require_verified_kyc_for_withdrawal();

-- Les fonctions de trigger ne sont jamais des API publiques.
revoke execute on function public.guard_profile_protected_fields() from public, anon, authenticated;
revoke execute on function public.log_kyc_status_change() from public, anon, authenticated;
revoke execute on function public.request_kyc_after_acceptance() from public, anon, authenticated;
revoke execute on function public.require_verified_kyc_for_withdrawal() from public, anon, authenticated;
revoke execute on function public.guard_structure_verification_fields() from public, anon, authenticated;

revoke execute on function public.guard_structure_verification() from public, anon, authenticated;
